language: python

python:
  - "2.7"
  # For simulator
  # - "pypy"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install google-perftools
install:
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - pip install --quiet -U pip setuptools wheel
  - pip install --quiet --only-binary=numpy,scipy 'numpy>=1.14.0' 'scipy>=1.0.0'
  - pip install -r src/requirements.txt
script:
  - pytest -s test --ignore=test/test_inference.py
  # Eventually: supply data and tensorflow
  # - pytest -s test --tf_dir /path/to/tensorflow \ --data_dir /path/to/training/data
cache:
  pip: true
