language: python

python:
  - "2.7"
  # For simulator
  # - "pypy"
install:
  - pip install --quiet -U pip setuptools wheel
  - pip install --quiet --only-binary=numpy,scipy numpy scipy
  - pip install -r src/requirements.txt
script:
  - pytest -s test --ignore=test/test_inference.py
  # Eventually: supply data and tensorflow
  # - pytest -s test --tf_dir /path/to/tensorflow \ --data_dir /path/to/training/data
cache:
  pip: true
