#!/bin/bash
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-cars-cats-500 -m f1 --datasets cars cats > log/distributed/inception-f1-cars-cats-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-cars-pedestrian-500 -m f1 --datasets cars pedestrian > log/distributed/inception-f1-cars-pedestrian-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-cars-train-500 -m f1 --datasets cars train > log/distributed/inception-f1-cars-train-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-cars-flowers-500 -m f1 --datasets cars flowers > log/distributed/inception-f1-cars-flowers-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-cats-pedestrian-500 -m f1 --datasets cats pedestrian > log/distributed/inception-f1-cats-pedestrian-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-cats-train-500 -m f1 --datasets cats train > log/distributed/inception-f1-cats-train-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-cats-flowers-500 -m f1 --datasets cats flowers > log/distributed/inception-f1-cats-flowers-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-pedestrian-train-500 -m f1 --datasets pedestrian train > log/distributed/inception-f1-pedestrian-train-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-pedestrian-flowers-500 -m f1 --datasets pedestrian flowers > log/distributed/inception-f1-pedestrian-flowers-500-mainstream-simulator.out
sem -j+0 python src/scheduler/run_scheduler_simulator.py 20 ../mainstream-analysis/output/streamer/scheduler/distributed/f1/inception/f1-train-flowers-500 -m f1 --datasets train flowers > log/distributed/inception-f1-train-flowers-500-mainstream-simulator.out
sem --wait
